[package]
name = "sidex-serde"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1"
# Required for serializing and deserializing Base64 encoded bytes.
base64 = "0.20"  # PRIVATE

[features]
serde-private-content = []
default = []